<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="lekarze.xsl"?>
<!DOCTYPE lekarze 
[
<!ATTLIST lekarz id CDATA #REQUIRED>
<!ELEMENT imie (#PCDATA)>
<!ELEMENT nazwisko (#PCDATA)>
<!ELEMENT specjalizacja (#PCDATA)>
<!ELEMENT lekarz (imie,nazwisko,specjalizacja)>
]>
<lekarze>
	<lekarz id="1">
		<imie>Janusz</imie>
		<nazwisko>Mondry</nazwisko>
		<specjalizacja>Internista</specjalizacja>
	</lekarz>
	<lekarz id="2">
		<imie>Halina</imie>
		<nazwisko>Szybcial</nazwisko>
		<specjalizacja>Radiolog</specjalizacja>
	</lekarz>
	<lekarz id="3">
		<imie>Mariusz</imie>
		<nazwisko>Åšniady</nazwisko>
		<specjalizacja>Chirurg</specjalizacja>
	</lekarz>
</lekarze>



