<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="pacjenci.xsl"?>
<!DOCTYPE pacjenci 
[
<!ATTLIST pacjent id CDATA #REQUIRED>
<!ELEMENT imie (#PCDATA)>
<!ELEMENT nazwisko (#PCDATA)>
<!ELEMENT adres (#PCDATA)>
<!ELEMENT pacjent (imie,nazwisko,adres)>
]>
<pacjenci>
	<pacjent id="1">
		<imie>Janusz</imie>
		<nazwisko>Kowalski</nazwisko>
		<adres>Pierwsza 1 00-999 Warszawa</adres>
	</pacjent>
	<pacjent id="2">
		<imie>Celina</imie>
		<nazwisko>Cebulska</nazwisko>
		<adres>Druga 2 00-999 Warszawa</adres>
	</pacjent>
	<pacjent id="3">
		<imie>Andrzej</imie>
		<nazwisko>Prosty</nazwisko>
		<adres>Trzecia 3 00-999 Warszawa</adres>
	</pacjent>
	<pacjent id="4">
		<imie>Ania</imie>
		<nazwisko>Budzik</nazwisko>
		<adres>Czwarta 4 00-999 Warszawa</adres>
	</pacjent>
	<pacjent id="5">
		<imie>Zbigniewa</imie>
		<nazwisko>Krzaczasta</nazwisko>
		<adres>Piąta 5 00-999 Warszawa</adres>
	</pacjent>
	<pacjent id="6">
		<imie>Marian</imie>
		<nazwisko>Rybak</nazwisko>
		<adres>Szósta 6 00-999 Warszawa</adres>
	</pacjent>
	<pacjent id="7">
		<imie>Mateusz</imie>
		<nazwisko>Linijkarz</nazwisko>
		<adres>Siódma 7 00-999 Warszawa</adres>
	</pacjent>
</pacjenci>